version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
workflows:
  version: 2.1
  run-tests:
    jobs:
      - test