version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout
      - run:
          name: Run Tests
          command: yarn test
workflows:
  version: 2.1
  run-tests:
    jobs:
      - test