version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - rev1-npm-deps-{{ checksum "yarn.lock" }}
            - rev1-npm-deps-
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run Tests
          command: yarn test
      - save_cache:
          key: rev1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
workflows:
  version: 2.1
  run-tests:
    jobs:
      - build_and_test
